apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: algorithm-visualization
  namespace: algorithm-visualization
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: algorithms.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: algorithm-visualization
                port:
                  name: http
